version: "3.9"

services:
  laravelapp:
    container_name: NewsAggregator
    build: .
    restart: always
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - laravel
    environment:
      - DB_HOST=mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - pgdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    networks:
      - laravel
      
volumes:
  pgdata: {}
    
networks:
  laravel:
